# Copyright (C) 2022 vscode
#
# This file is part of LibreFoodPantry.
#
# LibreFoodPantry is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LibreFoodPantry is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LibreFoodPantry.  If not, see <http://www.gnu.org/licenses/>.

name: Release Image

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: docker://ghcr.io/codfish/semantic-release-action@sha256:43a9e5ce88fc0460c22f3f3c45e39ac99e1cefff2ffd76c6e8c34306c8ccec91
        id: semantic
        with:
          branches: |
            [
              'main'
            ]
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              '@semantic-release/github'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/hfossedu/gitkit-deploy
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        if: steps.semantic.outputs.new-release-published == 'true'
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ghcr.io/hfossedu/gitkit-deploy:${{ steps.semantic.outputs.release-version }}
            ghcr.io/hfossedu/gitkit-deploy:${{ steps.semantic.outputs.release-major }}.${{ steps.semantic.outputs.release-minor }}
            ghcr.io/hfossedu/gitkit-deploy:${{ steps.semantic.outputs.release-major }}
            ghcr.io/hfossedu/gitkit-deploy:latest
